### PR TITLE
Upgrade Cake to 0.17.0

### PR DESCRIPTION
**Pull request by devlead**
Cake 0.18.0 will requires at least version 0.16.x to work.

### CODE REVIEW

**Comment by aabenoja** [comment]
Looking at upgrading one of our projects to 0.19 and I'm currently getting hit with the "need to reference at least Cake.Core version 0.16.0" error. Is there an eta on a release for this?

**Comment by gep13** [comment]
@aabenoja this is on my list to tackle, along with updating this repository to use Cake.Recipe.  It could be that @philo will have a chance to get to this first though.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@devlead thank you for making this change!

**Comment by gep13** [comment]
@aabenoja I have just pushed a new nuget package to NuGet.org for Cake.Webpack.

Can you please take it for a spin, and let me know if you run into any issues.

Thanks!

**Pull request merged**
