### PR TITLE
Issue #6 - Update Cake.Core to 0.22.0 (or higher)

### PR DESCRIPTION
**Pull request by JeremyCade**
- Nuget Target: net46
- Update projects to .NET 4.6.1
- Upgrade Cake.Core dependencies to 0.23.0 (current)
- Upgrade Shoudly dependency 2.8.3
- Upgrade xUnit.net dependencies to 2.3.1

### CODE REVIEW

**Comment by JeremyCade** [comment]
@gep13, @devlead Would either of you be able to point me in the right direction as to why the Deploy-Graph-Documentation step in the AppVeyor build is failing?

More than happy to fix, not sure where to start with that.

**Comment by gep13** [comment]
@JeremyCade Cake.Graph hasn't been updated to work with Cake 0.23.0. If you pin to 0.22.2 in your packages.config file it should all work for you.

**Comment by JeremyCade** [comment]
@gep13 appreciate the help. 

Ran into the same issue. I'll try and find some time over the next few days to dig into what is going on. No doubt I will run into similar problems in the future. Best to spend the time now to gain a better understanding of the addin build process.

**Comment by gep13** [comment]
@JeremyCade the PR is still using 0.23.0 of Cake, as you can see here:

https://ci.appveyor.com/project/cakecontrib/cake-webpack/build/0.3.0-PullRequest.7+6.build.16#L205

To be clear, it is the packages.config file in the tools folder that needs to be pinned at 0.22.2.  The version of Cake that you reference from your addin can be 0.23.0, but the version of Cake that actually runs your build needs to be 0.22.2.

**Comment by JeremyCade** [comment]
That's an oversight on my part. @gep13 thank you for pointing that out.

**Comment by gep13** [comment]
@JeremyCade you are very welcome.

**Comment by gep13** [comment]
@JeremyCade as a side note...

Is this work going out as a hotfix release?  I noticed that you are targetting the work against the master branch.  This repository is set up using gitflow, i.e. having both a master and a develop branch.  If this isn't a hotfix piece of work, the change should really be targetted for the develop branch, and then moved to the master branch via a release branch.

**Comment by JeremyCade** [comment]
@gep13 I've retargeted the pull request against the develop branch.  

Would you prefer that I close this pull request and create a new one from Develop to Develop?

**Comment by gep13** [comment]
I think re-targetting is fine, but you will need to reset your fork once the merge into develop on this repository happens, as your master will then be out of sync.

**Comment by JeremyCade** [comment]
Not a problem. I'll reset my fork when the time comes.

**Comment by gep13** [comment]
:+1:

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@JeremyCade thanks for doing this work!

**Pull request merged**
